#!/usr/bin/env python3
"""Turns the Free Exercise DB into a Vela migration: the shipped exercise library.

    curl -sL -o exercises.json \\
      https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json
    python3 scripts/exercise-library-migration.py exercises.json [stamp]

Writes supabase/migrations/<stamp>_exercise_library.sql: some 870 exercises as library rows
(coach_id null, so every coach reads them and none can edit them), each with its
instructions as cues, its muscles in Vela's vocabulary, its equipment, and a note saying
what kind of movement it is. The dataset is public domain (The Unlicense), so nothing is
owed for shipping it.

Ids are deterministic (uuid5 of the dataset's own id) so a refresh is an upsert. A row
whose name already exists in the library under another id is skipped: the sixteen
exercises Vela shipped with are hand-written for this population and stay as they are.
"""
import datetime, json, os, sys, uuid

src = sys.argv[1]
stamp = sys.argv[2] if len(sys.argv) > 2 else datetime.datetime.utcnow().strftime('%Y%m%d%H%M%S')
out = os.path.join(os.path.dirname(__file__), '..', 'supabase', 'migrations', f'{stamp}_exercise_library.sql')
NS = uuid.UUID('9c2a7d4e-5b1f-4c8a-8e6d-3f2b1a0c9d8e')

rows = json.load(open(src))
assert len(rows) > 800, len(rows)

# The dataset's categories onto Vela's. Vela has no "cardio"; those fourteen (rowing,
# cycling, skipping, treadmill) go under running, the nearest thing.
CATEGORY = {
    'strength': 'strength',
    'powerlifting': 'strength',
    'olympic weightlifting': 'strength',
    'strongman': 'strength',
    'stretching': 'mobility',
    'plyometrics': 'plyometric',
    'cardio': 'running',
}

# The dataset's muscles onto the words the library already uses.
MUSCLE = {
    'quadriceps': 'quads',
    'hamstrings': 'hamstrings',
    'glutes': 'glutes',
    'calves': 'calves',
    'abdominals': 'core',
    'lower back': 'back',
    'middle back': 'back',
    'lats': 'back',
    'traps': 'back',
    'chest': 'chest',
    'shoulders': 'shoulders',
    'biceps': 'arms',
    'triceps': 'arms',
    'forearms': 'arms',
    'adductors': 'hips',
    'abductors': 'hips',
    'neck': 'neck',
}

EQUIPMENT = {
    None: 'Bodyweight',
    'body only': 'Bodyweight',
    'barbell': 'Barbell',
    'dumbbell': 'Dumbbell',
    'cable': 'Cable',
    'machine': 'Machine',
    'kettlebells': 'Kettlebell',
    'bands': 'Band',
    'medicine ball': 'Medicine ball',
    'exercise ball': 'Exercise ball',
    'foam roll': 'Foam roller',
    'e-z curl bar': 'EZ bar',
    'other': 'Other',
}


def lit(s):
    if s is None:
        return 'null'
    return "'" + str(s).replace("'", "''") + "'"


def arr(items):
    return 'ARRAY[' + ','.join(lit(i) for i in items) + ']::text[]' if items else "'{}'::text[]"


def muscles(row):
    seen = []
    for m in row.get('primaryMuscles', []) + row.get('secondaryMuscles', []):
        v = MUSCLE.get(m)
        if v and v not in seen:
            seen.append(v)
    return seen


def note(row):
    parts = []
    if row.get('level'):
        parts.append(row['level'].capitalize())
    if row.get('mechanic'):
        parts.append(row['mechanic'])
    if row.get('force'):
        parts.append(row['force'])
    what = ', '.join(parts)
    return f"{what}. From the Free Exercise DB (public domain)." if what else 'From the Free Exercise DB (public domain).'


lines = [
    f"-- The shipped exercise library: {len(rows)} movements from the Free Exercise DB",
    "-- (https://github.com/yuhonas/free-exercise-db, public domain under The Unlicense).",
    "-- Generated by scripts/exercise-library-migration.py; do not edit by hand.",
    "--",
    "-- Library rows have no coach: every coach reads them, none edits them. A row whose name",
    "-- is already in the library under another id is left alone — the exercises Vela shipped",
    "-- with are written for this population and take precedence.",
    "",
]

batch = []


def flush():
    if not batch:
        return
    lines.append(
        "insert into public.exercises (id, coach_id, name, category, cues, muscle_groups, equipment, notes)\n"
        "select v.id::uuid, null, v.name, v.category::public.exercise_category, v.cues, v.muscle_groups, v.equipment, v.notes\n"
        "from (values"
    )
    lines.append(',\n'.join(batch))
    lines.append(
        ") as v (id, name, category, cues, muscle_groups, equipment, notes)\n"
        "where not exists (\n"
        "  select 1 from public.exercises x\n"
        "  where x.coach_id is null and lower(x.name) = lower(v.name) and x.id <> v.id::uuid\n"
        ")\n"
        "on conflict (id) do update set\n"
        "  name = excluded.name, category = excluded.category, cues = excluded.cues,\n"
        "  muscle_groups = excluded.muscle_groups, equipment = excluded.equipment, notes = excluded.notes,\n"
        "  updated_at = now();\n"
    )
    batch.clear()


seen_names = set()
count = 0
for row in sorted(rows, key=lambda r: r['id']):
    name = row['name'].strip()
    key = name.lower()
    if key in seen_names:
        continue
    seen_names.add(key)
    category = CATEGORY.get(row.get('category'))
    if category is None:
        continue
    uid = uuid.uuid5(NS, row['id'])
    cues = [c.strip() for c in row.get('instructions', []) if c and c.strip()]
    batch.append(
        f"({lit(uid)}, {lit(name)}, {lit(category)}, {arr(cues)}, {arr(muscles(row))}, "
        f"{lit(EQUIPMENT.get(row.get('equipment'), 'Other'))}, {lit(note(row))})"
    )
    count += 1
    if len(batch) >= 200:
        flush()
flush()

open(out, 'w').write('\n'.join(lines) + '\n')
print(out, count, 'exercises', os.path.getsize(out) // 1024, 'KB')
