#!/usr/bin/env python3
"""Turns the delivered USDA SQLite reference into a Vela data migration.

    python3 scripts/usda-foods-migration.py path/to/coach_food_db_v1.sqlite

Writes supabase/migrations/<stamp>_usda_foods_data.sql: the foods (per 100 g, with the
single most natural serving, the search boost and the aliases), their household portions,
and the policy and constraint changes that let a USDA row exist beside a coach's own and a
scanned product. Ids are deterministic (uuid5 of the USDA number) so a refresh is an
upsert by ndb_no, never a renumbering. Nutrient values are copied, never recomputed.
"""
import sqlite3, sys, uuid, os, datetime

src = sys.argv[1]
stamp = sys.argv[2] if len(sys.argv) > 2 else datetime.datetime.utcnow().strftime('%Y%m%d%H%M%S')
out = os.path.join(os.path.dirname(__file__), '..', 'supabase', 'migrations', f'{stamp}_usda_foods_data.sql')
NS = uuid.UUID('6f7a1f3e-2d0b-4b6e-9a3d-7b1c4d5e6f70')
c = sqlite3.connect(src)
assert c.execute('pragma integrity_check').fetchone()[0] == 'ok'
n_foods = c.execute('select count(*) from foods').fetchone()[0]
assert n_foods > 8000, n_foods

def lit(s):
    if s is None: return 'null'
    return "'" + str(s).replace("'", "''") + "'"
def num(x):
    return 'null' if x is None else repr(round(float(x), 2))
def arr(items):
    return 'ARRAY[' + ','.join(lit(i) for i in items) + ']::text[]' if items else "'{}'::text[]"

groups = dict(c.execute('select id, name from food_groups'))

# The foods people type most, lifted half a point so that among the entries whose head is
# the typed word the everyday form comes first: whole milk before human milk, raw salmon
# before canned, cooked rice before rice bran. Keyed by USDA number so a refresh keeps it.
STAPLES = {
    '01001', '01009', '01040', '01077', '01079', '01085', '01116', '01123', '01256', '04053',
    '05006', '05062', '05064', '08121', '09003', '09037', '09040', '09148', '09150', '09200',
    '09252', '09266', '09316', '10060', '11090', '11124', '11167', '11205', '11215', '11233',
    '11260', '11282', '11362', '11367', '11457', '11507', '11510', '11529', '11821', '12061',
    '12220', '13047', '14209', '15015', '15076', '15121', '15236', '16057', '16070', '16087',
    '16098', '16126', '18069', '18075', '19165', '19296', '20037', '20038', '20045', '20121',
    '20137', '23572',
}
STAPLE_LIFT = 0.5

# Words people type that the reference spells differently, added to the search aliases of
# the entry they mean.
EXTRA_ALIASES = {
    '08121': ['oatmeal', 'porridge'],
    '20038': ['oatmeal', 'rolled oats', 'porridge oats'],
    '01077': ['full fat milk', 'whole milk'],
    '01079': ['semi skimmed milk', 'semi-skimmed milk'],
    '01085': ['skimmed milk', 'skim milk'],
    '05062': ['chicken breast', 'chicken fillet'],
    '20045': ['white rice'],
    '20037': ['brown rice'],
    '18075': ['wholemeal bread', 'brown bread'],
    '16057': ['chickpeas', 'garbanzo'],
    '01256': ['greek yogurt', 'greek yoghurt'],
}
aliases = {}
for food_id, alias in c.execute('select food_id, alias from aliases'):
    aliases.setdefault(food_id, []).append(alias)

lines = [f"-- The USDA Standard Reference 28 generic-foods reference: {n_foods} foods, their household",
         "-- portions and search aliases. Generated by scripts/usda-foods-migration.py from the",
         "-- delivered SQLite file; do not edit by hand. Nutrient data from the USDA National",
         "-- Nutrient Database for Standard Reference, Agricultural Research Service, U.S.",
         "-- Department of Agriculture. Public domain.",
         "",
         "-- A USDA row has no owner and no barcode.",
         "alter table public.foods drop constraint if exists foods_ownership;",
         "alter table public.foods add constraint foods_ownership check (",
         "  (source = 'off' and coach_id is null and barcode is not null)",
         "  or (source = 'custom' and coach_id is not null)",
         "  or (source = 'usda' and coach_id is null)",
         ");",
         "",
         "drop policy if exists foods_read on public.foods;",
         "create policy foods_read on public.foods for",
         "select",
         "  using (",
         "    source in ('off', 'usda')",
         "    or coach_id = auth.uid()",
         "    or coach_id = (select c.coach_id from public.clients c where c.profile_id = auth.uid())",
         "  );",
         ""]

rows = c.execute('select id, ndb_no, name, food_group_id, kcal, protein_g, carbs_g, fat_g, serving_g, serving_label, rank_boost from foods order by id').fetchall()
ids = {}
batch = []
def flush_foods():
    if not batch: return
    lines.append("insert into public.foods (id, source, name, food_group, kcal_100g, protein_100g, carbs_100g, fat_100g, serving_g, serving_name, ndb_no, rank_boost, aliases) values")
    lines.append(',\n'.join(batch) + '\non conflict (ndb_no) do update set name = excluded.name, food_group = excluded.food_group, kcal_100g = excluded.kcal_100g, protein_100g = excluded.protein_100g, carbs_100g = excluded.carbs_100g, fat_100g = excluded.fat_100g, serving_g = excluded.serving_g, serving_name = excluded.serving_name, rank_boost = excluded.rank_boost, aliases = excluded.aliases;')
    batch.clear()
for fid, ndb, name, group, kcal, prot, carbs, fat, sg, sl, boost in rows:
    uid = uuid.uuid5(NS, f'usda:{ndb}'); ids[fid] = str(uid)
    batch.append(f"({lit(uid)}, 'usda', {lit(name)}, {lit(groups.get(group))}, {num(kcal)}, {num(prot or 0)}, {num(carbs or 0)}, {num(fat or 0)}, {num(sg)}, {lit(sl)}, {lit(ndb)}, {num((boost or 1) + (STAPLE_LIFT if ndb in STAPLES else 0))}, {arr(aliases.get(fid, []) + EXTRA_ALIASES.get(ndb, []))})")
    if len(batch) >= 400: flush_foods()
flush_foods()

lines.append("")
lines.append("-- Portions are replaced wholesale for USDA foods, so a refresh never leaves stale ones.")
lines.append("delete from public.food_portions where food_id in (select id from public.foods where source = 'usda');")
pb = []
def flush_portions():
    if not pb: return
    lines.append("insert into public.food_portions (food_id, seq, label, gram_weight) values")
    lines.append(',\n'.join(pb) + ';')
    pb.clear()
for fid, seq, label, grams in c.execute('select food_id, seq, label, gram_weight from portions order by food_id, seq'):
    if fid not in ids or grams is None or float(grams) <= 0: continue
    pb.append(f"({lit(ids[fid])}, {int(seq)}, {lit(label)}, {num(grams)})")
    if len(pb) >= 800: flush_portions()
flush_portions()

open(out, 'w').write('\n'.join(lines) + '\n')
print(out, os.path.getsize(out) // 1024, 'KB')
